version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    pre-build:
      commands:
        - npm install
    build:
      commands:
        - npm build
        - npm test
    artifacts:
      files:
        - src/**/*
        - package.json 
